// Auto-generated by scripts/generate-image-manifest.mjs
// Do not edit this file manually

export type ImageManifest = Record<string, string>;

const imageManifest: ImageManifest = {
  "cauliflower-coconut-espuma/bloemkool.jpg": "3b38cfe4",
  "celeriac-mushroom-espuma/celeriac-espuma.jpg": "f520d490",
  "chocolate-panna-cotta-orange/panna-cotta-chock.jpg": "44e60078",
  "lime-parfait-meringue-caramelized-white-chocolate/lime-parfait.jpg": "abd3ff36",
  "roasted-celeriac-steak-caramelized-shallots/celeriac-steak.jpg": "830cb9f6",
  "sous-vide-veal-cheeks-langoustine/veal-cheeks.jpg": "7b2a375c",
  "spicy-seared-scallops-mango-soy/scallops.jpg": "aa33d2f5",
  "spicy-white-chocolate-mousse/spicy-white-cholate-mouse.jpg": "bc227bd6",
  "steak-with-beetroot-tartare/ree.jpg": "06d8ab9e",
  "tuna-tataki/tuna-tetaki.jpg": "29b7351f"
};

export default imageManifest;
